#ifndef _GENERIC_H_
#define _GENERIC_H_

/* Generated by WriteClassHeaderVisitor: Fri Mar 31 2023 16:34:00 GMT-0600 (Mountain Daylight Time) */

#ifdef INCLUDE_PRIVATE
typedef struct _PhidgetGeneric *PhidgetGenericHandle;

/* Methods */
API_PRETURN_HDR PhidgetGeneric_create(PhidgetGenericHandle *ch);
API_PRETURN_HDR PhidgetGeneric_delete(PhidgetGenericHandle *ch);

/* Properties */

/* Events */

#endif /* INCLUDE_PRIVATE */
#endif /* _GENERIC_H_ */
