// Generated by gencpp from file global_controller/gps_points.msg
// DO NOT EDIT!


#ifndef GLOBAL_CONTROLLER_MESSAGE_GPS_POINTS_H
#define GLOBAL_CONTROLLER_MESSAGE_GPS_POINTS_H

#include <ros/service_traits.h>


#include <global_controller/gps_pointsRequest.h>
#include <global_controller/gps_pointsResponse.h>


namespace global_controller
{

struct gps_points
{

typedef gps_pointsRequest Request;
typedef gps_pointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gps_points
} // namespace global_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::global_controller::gps_points > {
  static const char* value()
  {
    return "b5bec956a12980a00e59b3e48c455bdc";
  }

  static const char* value(const ::global_controller::gps_points&) { return value(); }
};

template<>
struct DataType< ::global_controller::gps_points > {
  static const char* value()
  {
    return "global_controller/gps_points";
  }

  static const char* value(const ::global_controller::gps_points&) { return value(); }
};


// service_traits::MD5Sum< ::global_controller::gps_pointsRequest> should match
// service_traits::MD5Sum< ::global_controller::gps_points >
template<>
struct MD5Sum< ::global_controller::gps_pointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::global_controller::gps_points >::value();
  }
  static const char* value(const ::global_controller::gps_pointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_controller::gps_pointsRequest> should match
// service_traits::DataType< ::global_controller::gps_points >
template<>
struct DataType< ::global_controller::gps_pointsRequest>
{
  static const char* value()
  {
    return DataType< ::global_controller::gps_points >::value();
  }
  static const char* value(const ::global_controller::gps_pointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::global_controller::gps_pointsResponse> should match
// service_traits::MD5Sum< ::global_controller::gps_points >
template<>
struct MD5Sum< ::global_controller::gps_pointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::global_controller::gps_points >::value();
  }
  static const char* value(const ::global_controller::gps_pointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_controller::gps_pointsResponse> should match
// service_traits::DataType< ::global_controller::gps_points >
template<>
struct DataType< ::global_controller::gps_pointsResponse>
{
  static const char* value()
  {
    return DataType< ::global_controller::gps_points >::value();
  }
  static const char* value(const ::global_controller::gps_pointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GLOBAL_CONTROLLER_MESSAGE_GPS_POINTS_H
