// Generated by gencpp from file global_controller/gps_pointsResponse.msg
// DO NOT EDIT!


#ifndef GLOBAL_CONTROLLER_MESSAGE_GPS_POINTSRESPONSE_H
#define GLOBAL_CONTROLLER_MESSAGE_GPS_POINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace global_controller
{
template <class ContainerAllocator>
struct gps_pointsResponse_
{
  typedef gps_pointsResponse_<ContainerAllocator> Type;

  gps_pointsResponse_()
    : reached_status(false)  {
    }
  gps_pointsResponse_(const ContainerAllocator& _alloc)
    : reached_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reached_status_type;
  _reached_status_type reached_status;





  typedef boost::shared_ptr< ::global_controller::gps_pointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::global_controller::gps_pointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct gps_pointsResponse_

typedef ::global_controller::gps_pointsResponse_<std::allocator<void> > gps_pointsResponse;

typedef boost::shared_ptr< ::global_controller::gps_pointsResponse > gps_pointsResponsePtr;
typedef boost::shared_ptr< ::global_controller::gps_pointsResponse const> gps_pointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::global_controller::gps_pointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::global_controller::gps_pointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::global_controller::gps_pointsResponse_<ContainerAllocator1> & lhs, const ::global_controller::gps_pointsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reached_status == rhs.reached_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::global_controller::gps_pointsResponse_<ContainerAllocator1> & lhs, const ::global_controller::gps_pointsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace global_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::global_controller::gps_pointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::global_controller::gps_pointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::global_controller::gps_pointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::global_controller::gps_pointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_controller::gps_pointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_controller::gps_pointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::global_controller::gps_pointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a7f193d6d3387641f8cb3e2fb24e17d";
  }

  static const char* value(const ::global_controller::gps_pointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a7f193d6d338764ULL;
  static const uint64_t static_value2 = 0x1f8cb3e2fb24e17dULL;
};

template<class ContainerAllocator>
struct DataType< ::global_controller::gps_pointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "global_controller/gps_pointsResponse";
  }

  static const char* value(const ::global_controller::gps_pointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::global_controller::gps_pointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reached_status\n"
;
  }

  static const char* value(const ::global_controller::gps_pointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::global_controller::gps_pointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reached_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gps_pointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::global_controller::gps_pointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::global_controller::gps_pointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "reached_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reached_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLOBAL_CONTROLLER_MESSAGE_GPS_POINTSRESPONSE_H
