// Generated by gencpp from file global_controller/gps_pointsRequest.msg
// DO NOT EDIT!


#ifndef GLOBAL_CONTROLLER_MESSAGE_GPS_POINTSREQUEST_H
#define GLOBAL_CONTROLLER_MESSAGE_GPS_POINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace global_controller
{
template <class ContainerAllocator>
struct gps_pointsRequest_
{
  typedef gps_pointsRequest_<ContainerAllocator> Type;

  gps_pointsRequest_()
    : latitude(0.0)
    , longitude(0.0)  {
    }
  gps_pointsRequest_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;





  typedef boost::shared_ptr< ::global_controller::gps_pointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::global_controller::gps_pointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gps_pointsRequest_

typedef ::global_controller::gps_pointsRequest_<std::allocator<void> > gps_pointsRequest;

typedef boost::shared_ptr< ::global_controller::gps_pointsRequest > gps_pointsRequestPtr;
typedef boost::shared_ptr< ::global_controller::gps_pointsRequest const> gps_pointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::global_controller::gps_pointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::global_controller::gps_pointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::global_controller::gps_pointsRequest_<ContainerAllocator1> & lhs, const ::global_controller::gps_pointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::global_controller::gps_pointsRequest_<ContainerAllocator1> & lhs, const ::global_controller::gps_pointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace global_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::global_controller::gps_pointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::global_controller::gps_pointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::global_controller::gps_pointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::global_controller::gps_pointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_controller::gps_pointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_controller::gps_pointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::global_controller::gps_pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "680c6dc7da65a2421a822205dcbdb600";
  }

  static const char* value(const ::global_controller::gps_pointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x680c6dc7da65a242ULL;
  static const uint64_t static_value2 = 0x1a822205dcbdb600ULL;
};

template<class ContainerAllocator>
struct DataType< ::global_controller::gps_pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "global_controller/gps_pointsRequest";
  }

  static const char* value(const ::global_controller::gps_pointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::global_controller::gps_pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
;
  }

  static const char* value(const ::global_controller::gps_pointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::global_controller::gps_pointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gps_pointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::global_controller::gps_pointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::global_controller::gps_pointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLOBAL_CONTROLLER_MESSAGE_GPS_POINTSREQUEST_H
