// Generated by gencpp from file waypoint_driver/gps_points.msg
// DO NOT EDIT!


#ifndef WAYPOINT_DRIVER_MESSAGE_GPS_POINTS_H
#define WAYPOINT_DRIVER_MESSAGE_GPS_POINTS_H

#include <ros/service_traits.h>


#include <waypoint_driver/gps_pointsRequest.h>
#include <waypoint_driver/gps_pointsResponse.h>


namespace waypoint_driver
{

struct gps_points
{

typedef gps_pointsRequest Request;
typedef gps_pointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gps_points
} // namespace waypoint_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::waypoint_driver::gps_points > {
  static const char* value()
  {
    return "b5bec956a12980a00e59b3e48c455bdc";
  }

  static const char* value(const ::waypoint_driver::gps_points&) { return value(); }
};

template<>
struct DataType< ::waypoint_driver::gps_points > {
  static const char* value()
  {
    return "waypoint_driver/gps_points";
  }

  static const char* value(const ::waypoint_driver::gps_points&) { return value(); }
};


// service_traits::MD5Sum< ::waypoint_driver::gps_pointsRequest> should match
// service_traits::MD5Sum< ::waypoint_driver::gps_points >
template<>
struct MD5Sum< ::waypoint_driver::gps_pointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_driver::gps_points >::value();
  }
  static const char* value(const ::waypoint_driver::gps_pointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_driver::gps_pointsRequest> should match
// service_traits::DataType< ::waypoint_driver::gps_points >
template<>
struct DataType< ::waypoint_driver::gps_pointsRequest>
{
  static const char* value()
  {
    return DataType< ::waypoint_driver::gps_points >::value();
  }
  static const char* value(const ::waypoint_driver::gps_pointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::waypoint_driver::gps_pointsResponse> should match
// service_traits::MD5Sum< ::waypoint_driver::gps_points >
template<>
struct MD5Sum< ::waypoint_driver::gps_pointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::waypoint_driver::gps_points >::value();
  }
  static const char* value(const ::waypoint_driver::gps_pointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::waypoint_driver::gps_pointsResponse> should match
// service_traits::DataType< ::waypoint_driver::gps_points >
template<>
struct DataType< ::waypoint_driver::gps_pointsResponse>
{
  static const char* value()
  {
    return DataType< ::waypoint_driver::gps_points >::value();
  }
  static const char* value(const ::waypoint_driver::gps_pointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINT_DRIVER_MESSAGE_GPS_POINTS_H
